#!/usr/bin/env python
import sys

from aplparser import APL

def parse_only(src):
    p = APL(debug=True)
    tokens = p.tokenise(src)
    ast = p.parse(tokens)

    if ast is None:
        return None

    return str(ast)


ast = parse_only(sys.argv[1])

print(ast)
