#!/usr/bin/env python
import sys

from aplparser import APL

def parse_only(src):
    p = APL()
    tokens = p.tokenise(src)
    ast = p.parse(tokens)

    if ast is None:
        return None

    return str(ast)


print(parse_only(sys.argv[1]))
